version: 2

jobs:
  build:
    docker:
      - image: circleci/node:4.8.2

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache

      - run: npm install -g npm@5.6.0
      - run: npm install

      - save_cache:
          key: dependency-cache
          paths:
            - ./node_modules
      - run:
          name: Add NPM bin to path
          command: |
            echo 'export PATH=$PATH:$(npm bin)' >> $BASH_ENV
            source /home/circleci/.bashrc
      - run: gulp build